### ISSUE TITLE
Voice recognition development 

### ISSUE THREAD

**Issue by Anugaradhawa** [atomic14/voice-controlled-robot#12]
Can we develop this project to recognize the all commands we know?

**Comment by cgreening** [comment]
There's a limit to what you can do with a model small enough to run quickly on an esp32.

You can use a larger more complex model with more preprocessing and recognise more words, but you might struggle to get it to run on the esp32.

**Comment by Anugaradhawa** [comment]
what type of development board I can run when I make a model like that? I have a question, the Alexa project and this voice control car's code is really written by yourself? or did you get this code from another person?

**Comment by cgreening** [comment]
You would probably find a raspberry pi more suitable.

Very strange question. Yes, I wrote the code.

**Comment by Anugaradhawa** [comment]
wow really awesome. you are a genius. These days  I am doing a C course after I will do a C++ course then I will try your projects. before I had not any knowledge now I have a  little bit of knowledge about C. I also want to write codes like you.
