### ISSUE TITLE
Missing files and folders

### ISSUE THREAD

**Issue by Nicosh81** [atomic14/voice-controlled-robot#14]
Hi. Sir, I have successfully uploaded the ready model to ESP and everything worked. Now, I want to train my model. But some files and folders that you mentioned don't exist in the dataset. For example, you mentioned "For my training, I add a lot more data to the _background_noise_ folder. I also created a _problem_noise_ folder and recorded sounds that seemed to confuse the model - low frequency humming noises around 100Hz seem to cause problems."  I don't know what to include in _problem_noise_ folder.  Could you please upload it somewhere so I can download it? Also in code there is _invalid. Is it also a folder that you added afterward?

**Comment by Anugaradhawa** [comment]
is this project work correctly

**Comment by cgreening** [comment]
@Nicosh81 I've uploaded those folders and made them available here:

https://data.atomic14.com/_mar_sounds_.zip
https://data.atomic14.com/_background_noise_.zip
https://data.atomic14.com/_problem_noise_.zip

_invalid is just the class that is used for non-command words.
