### ISSUE TITLE
Dear Mr.atomic14

### ISSUE THREAD

**Issue by maoyanru** [atomic14/voice-controlled-robot#4]
I encountered some problems. When I learned your project (Build your own Alexa with the ESP32 and TensorFlow Lite), I think your project (Voice Controlled Robot using the ESP32 and TensorFlow Lite) might be simpler, so I imported it into platfromIO Platform and (modified the port COM7) successfully compiled, but in the end it still failed to download to esp32, the port information screenshots are given to you.
                                                                            Thank you for taking the time to reply to me。           
![image](https://user-images.githubusercontent.com/23259959/119265938-4e603980-bc1b-11eb-967b-60db691afc67.png)
![image](https://user-images.githubusercontent.com/23259959/119265964-718ae900-bc1b-11eb-8042-1aab84df0098.png)
![image](https://user-images.githubusercontent.com/23259959/119266195-68e6e280-bc1c-11eb-9ea4-b87f7796b40f.png)

**Comment by cgreening** [comment]
Sorry about that - seems like some updates to the underlying libraries now conflict fixed with: 6a19d65
