### ISSUE TITLE
Dear atomic14: there are somes question need your help, please give me some advice, thanks

### ISSUE THREAD

**Issue by maoyanru** [atomic14/voice-controlled-robot#5]
I have downloaded your project and it can be sucessfully compiled by platfromIo.I have been studying  for a few days,and i think i still need your guidance.
1、Can this project be completed only with esp32 and INMP441?
2、How to connect esp32 and INMP441 (the pin of INMP441 is connected to esp32)。
3、Can i use oscilloscope to view the waveform of INMP441 after powering on INMP441 alone(to make sure the INMP441 i bought is usable)
4、How to use jupyter notebook and Google Speech Commands Dataset (v0.02) to train other command model?Looking forward to you giving me the jupyter notebook project in this video for study。

![image](https://user-images.githubusercontent.com/23259959/119677141-0aff0880-be71-11eb-83ea-e2fd4bd69bbb.png)
Follow this picture to connect INMP441 and esp32 pin

![image](https://user-images.githubusercontent.com/23259959/119677409-48639600-be71-11eb-972a-954dcb01a3d2.png)
this my hardware（esp32 and INMP441）,if i say "back"or "left" and then INMP441 detect key words,finally serial port print(testing successfully)~
                                                                                                               Think you for taking the time to reply my question
                                                                                                                your’s sincerely fans  Yao

**Comment by fabiodavide97** [comment]
Dear Atomic14, i would use this project for my accademic project so i want know how change the code using 2 motor DC 
Thanks for the answer

**Comment by cgreening** [comment]
The best place to start would be the code in `CommandProcessor.cpp` the `processCommand` function is responsible for deciding what to do for each detected command.

At the moment it is simply changing the PWM signal to each motor. If you have a motor control board then this would be the place to make the changes.

**Comment by cgreening** [comment]
@maoyanru did you solve the issues you were having?
