### ISSUE TITLE
Problem in Generate Training Data Command

### ISSUE THREAD

**Issue by biccius** [atomic14/voice-controlled-robot#9]
Hi Atomic.

This project is great. I tried the example source and was very amazed at the level of recognition of the example words.

So I tried to perform the same steps in jupyter as described in the file "Generate Training Data Command Recognition.ipynb" but at the step where it processes the words I get this as if it has not processed the words and so I have empty vectors

![immagine](https://user-images.githubusercontent.com/27350014/136031418-fa33ed1e-f247-4e4e-91e8-49caf2dc3198.png)

What am I doing wrong?

**Comment by cgreening** [comment]
Hi Biccius,

Did you download the training data? It looks like it's not finding any of the wav files.

**Comment by biccius** [comment]
Hi Chris

Yes, I installed Jupyter on Windows and followed the initial instructions which said to unpack the files in the speech-data folder.

![immagine](https://user-images.githubusercontent.com/27350014/136154696-fb0dad2f-d27a-4b9f-a935-8845b1df9fc6.png)

I copied "Generate Training Data Command Recognition.ipynb" into the "speech-data" folder and opened it from there. 

I left the file untouched and wanted to test it as per the example provided. I carry out the steps up to step 9 without any errors until I get the progress bars as in the figure above.

I think some function is failing to find the correct files or paths but everything looks right to me. Any ideas what it could be?

I have never used Jupyter and the tensorflow components, so my knowledge of them is very limited.

Thanks

**Comment by cgreening** [comment]
Ah, you should have left the ipynb file where it was - that's why it's not
working.

**Comment by Anugaradhawa** [comment]
I have a question regarding this project (https://github.com/atomic14/diy-alexa ), how do I import background audio files to the jupyter notebook? plz reply for this questions

**Comment by rezkymahardika** [comment]
i have some trouble in ln [10]

AttributeError: module 'tensorflow_io.python.api.experimental' has no attribute 'audio'

Any ideas what it could be?

thanks

**Comment by cgreening** [comment]
@rezkymahardika I'll take a look. Tensorflow is constantly changing so the API may have moved.

**Comment by cgreening** [comment]
Try now - should be fixed.
